// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

/**
 * SF Symbols to Material Icons mappings for TRAVI app.
 */
const MAPPING = {
  // Navigation
  "house.fill": "home",
  "map.fill": "map",
  "wallet.pass.fill": "account-balance-wallet",
  "person.2.fill": "people",
  "gearshape.fill": "settings",
  // Actions
  "paperplane.fill": "send",
  "plus": "add",
  "plus.circle.fill": "add-circle",
  "chevron.left": "chevron-left",
  "chevron.right": "chevron-right",
  "chevron.left.forwardslash.chevron.right": "code",
  "xmark": "close",
  "xmark.circle.fill": "cancel",
  "checkmark": "check",
  "checkmark.circle.fill": "check-circle",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.up": "arrow-upward",
  "arrow.down": "arrow-downward",
  // Travel
  "airplane": "flight",
  "airplane.departure": "flight-takeoff",
  "airplane.arrival": "flight-land",
  "bed.double.fill": "hotel",
  "fork.knife": "restaurant",
  "camera.fill": "photo-camera",
  "map": "map",
  "location.fill": "location-on",
  "location.north.fill": "navigation",
  "globe": "language",
  "star.fill": "star",
  "star": "star-border",
  "heart.fill": "favorite",
  "heart": "favorite-border",
  "clock.fill": "schedule",
  "calendar": "calendar-today",
  "tag.fill": "local-offer",
  "bag.fill": "shopping-bag",
  // Communication
  "message.fill": "message",
  "bubble.left.fill": "chat",
  "bell.fill": "notifications",
  "bell": "notifications-none",
  "magnifyingglass": "search",
  "mic.fill": "mic",
  // User
  "person.fill": "person",
  "person.crop.circle.fill": "account-circle",
  "shield.fill": "security",
  "lock.fill": "lock",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility-off",
  // Status
  "exclamationmark.triangle.fill": "warning",
  "info.circle.fill": "info",
  "cross.fill": "add",
  "sos": "sos",
  "waveform": "graphic-eq",
  // Points & Wallet
  "dollarsign.circle.fill": "monetization-on",
  "creditcard.fill": "credit-card",
  "gift.fill": "card-giftcard",
  "chart.bar.fill": "bar-chart",
  // Misc
  "photo.fill": "photo",
  "square.and.arrow.up": "share",
  "trash.fill": "delete",
  "pencil": "edit",
  "doc.fill": "description",
  "arrow.clockwise": "refresh",
  "ellipsis": "more-horiz",
  "ellipsis.circle": "more-horiz",
  // Extra icons
  "trash": "delete",
  "arrow.left.arrow.right": "swap-horiz",
  "arrow.up.arrow.down": "swap-vert",
  "arrow.triangle.2.circlepath": "sync",
  "flame.fill": "local-fire-department",
  "sparkles": "auto-awesome",
  "crown.fill": "workspace-premium",
  "trophy.fill": "emoji-events",
  "gamecontroller.fill": "sports-esports",
  "dice.fill": "casino",
  "percent": "percent",
  "qrcode": "qr-code",
  "qrcode.viewfinder": "qr-code-scanner",
  "barcode": "barcode-reader",
  "wifi": "wifi",
  "car.fill": "directions-car",
  "tram.fill": "tram",
  "ferry.fill": "directions-boat",
  "figure.walk": "directions-walk",
  "sun.max.fill": "wb-sunny",
  "cloud.rain.fill": "umbrella",
  "snowflake": "ac-unit",
  "thermometer": "thermostat",
  "wind": "air",
  "moon.fill": "nightlight-round",
  "bolt.fill": "bolt",
  "leaf.fill": "eco",
  "building.2.fill": "business",
  "building.columns.fill": "account-balance",
  "tent.fill": "cabin",
  "mountain.2.fill": "landscape",
  "beach.umbrella": "beach-access",
  "fork.knife.circle.fill": "restaurant",
  "cup.and.saucer.fill": "coffee",
  "wineglass.fill": "wine-bar",
  "music.note": "music-note",
  "theatermasks.fill": "theater-comedy",
  "paintbrush.fill": "brush",
  "books.vertical.fill": "menu-book",
  "figure.run": "directions-run",
  "figure.yoga": "self-improvement",
  "dumbbell.fill": "fitness-center",
  "cross.circle.fill": "local-hospital",
  "phone.fill": "phone",
  "envelope.fill": "email",
  "link": "link",
  "safari.fill": "explore",
  "map.circle.fill": "map",
  "pin.fill": "push-pin",
  "flag.fill": "flag",
  "bookmark.fill": "bookmark",
  "bookmark": "bookmark-border",
  "list.bullet": "list",
  "list.bullet.clipboard.fill": "assignment",
  "square.grid.2x2.fill": "grid-view",
  "slider.horizontal.3": "tune",
  "arrow.up.right.square.fill": "open-in-new",
  "doc.text.fill": "article",
  "ticket.fill": "confirmation-number",
  "bag.badge.plus": "add-shopping-cart",
  "cart.fill": "shopping-cart",
  "checkmark.seal.fill": "verified",
  "rosette": "military-tech",
  "medal.fill": "military-tech",
  "hands.clap.fill": "celebration",
  "face.smiling": "sentiment-satisfied-alt",
  "hand.thumbsup.fill": "thumb-up",
  "hand.thumbsdown.fill": "thumb-down",
  "person.3.fill": "groups",
  "person.badge.plus": "person-add",
  "bubble.left.and.bubble.right.fill": "forum",
  "photo.on.rectangle": "collections",
  "video.fill": "videocam",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "stop.fill": "stop",
  "speaker.wave.2.fill": "volume-up",
  "infinity": "all-inclusive",
  "circle.fill": "circle",
  "square.fill": "square",
  "triangle.fill": "change-history",
  "minus": "remove",
  "minus.circle.fill": "remove-circle",
  "equal": "drag-handle",
  "number": "tag",
  "at": "alternate-email",
  "mappin.fill": "location-on",
  "mappin": "location-on",
  "apple.logo": "phone-iphone",
  "house.circle.fill": "home",
  "person.2.wave.2.fill": "group-add",
  "arrow.up.left.and.arrow.down.right": "open-with",
  "chart.pie.fill": "pie-chart",
  "chart.line.uptrend.xyaxis": "show-chart",
  "suitcase.fill": "work",
  "suitcase": "work-outline",
  "doc.badge.plus": "note-add",
  "photo.badge.plus": "add-photo-alternate",
  "checkmark.rectangle.fill": "check-box",
  "exclamationmark.circle.fill": "error",
  "exclamationmark.circle": "error-outline",
  "info.circle": "info-outline",
  "arrow.down.circle.fill": "download",
  "arrow.up.circle.fill": "upload",
  "paperclip": "attach-file",
  "hand.raised.fill": "back-hand",
  "bubble.right.fill": "chat-bubble",
  "person.crop.circle": "account-circle",
  "clock": "access-time",
  "timer": "timer",
  "hourglass": "hourglass-empty",
  // Missing icons used in quiz
  "figure.hiking": "hiking",
  "sofa.fill": "weekend",
  "building.fill": "apartment",
  "figure.surfing": "surfing",
  "headphones": "headphones",
  "moon.stars.fill": "nights-stay",
  "music.note.list": "queue-music",
  "car.side.fill": "directions-car",
  "drop.fill": "water-drop",
} as unknown as IconMapping;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
