// Auto-generated from Travi.world — DO NOT EDIT MANUALLY

export const TRAVI_CULTURAL_DATA: Record<string, {
  headline: string;
  emoji: string;
  sections: Array<{
    id: string; icon: string; title: string; color: string; gradient: [string, string];
    items: Array<{ label: string; value: string; type: "do"|"dont"|"info"|"tip" }>;
  }>;
  visa?: Array<{ label: string; value: string; type: "do"|"dont"|"info"|"tip" }>;
}> = {
  'dubai': {
    headline: 'Dubai rises from Arabian desert sands as a testament to modern ambition, where the world\'s tallest building pierces the sky, artificial islands reshape coastlines, and traditional souks still trade gold and spices by the creek.',
    emoji: '🇦🇪',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respect Ramadan fasting', value: 'During Ramadan, avoid eating, drinking, or smoking in public during daylight hours to show respect for those fasting.', type: 'dont' },
          { label: 'Enjoy Ramadan evenings', value: 'Evenings during Ramadan are festive with special meals and decorations after sunset. It\'s a culturally rich time to visit if you respect the customs.', type: 'info' },
          { label: 'Friday holy day', value: 'Friday is the Islamic holy day and part of the weekend. Some businesses close for morning prayers, and metro hours may be reduced.', type: 'info' },
          { label: 'Respect local religion', value: 'Avoid criticizing the government or religion, as laws are strict regarding public speech.', type: 'dont' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Cover shoulders and knees', value: 'When in malls and public spaces, ensure your shoulders and knees are covered. Swimwear is only appropriate at beaches, pools, and waterparks.', type: 'do' },
          { label: 'Hair covering optional', value: 'Women are not required to cover their hair in public, except when visiting mosques as a sign of respect.', type: 'info' },
          { label: 'Pack modest clothing', value: 'Pack light layers that cover shoulders and knees for malls and attractions to respect local customs.', type: 'do' },
          { label: 'Avoid revealing clubwear', value: 'While Dubai is liberal, revealing clubwear is not appropriate for public spaces like malls or the Metro.', type: 'dont' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Alcohol in licensed venues', value: 'Alcohol is legal and available only at licensed venues such as hotel restaurants, bars, and clubs. Public intoxication is illegal.', type: 'info' },
          { label: 'No public drinking', value: 'You cannot drink alcohol in public spaces, on beaches (except hotel beach clubs), or in parks.', type: 'dont' },
          { label: 'Try local dishes', value: 'Don\'t miss out on traditional Emirati cuisine such as Al Harees and Machboos, as well as popular dishes like shawarma, falafel, and Arabic coffee.', type: 'do' },
          { label: 'Daytime Ramadan dining', value: 'During Ramadan, eating in public during daylight hours is prohibited. Hotel restaurants may screen eating areas.', type: 'dont' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Homosexuality illegal', value: 'Homosexuality is illegal in the UAE. LGBTQ+ travelers should be discreet about relationships in public.', type: 'dont' },
          { label: 'Public intoxication illegal', value: 'Public intoxication is strictly prohibited and can lead to arrest.', type: 'dont' },
          { label: 'Photography rules', value: 'Avoid photographing locals, especially women, without permission. Do not photograph government buildings, police, or military.', type: 'dont' },
          { label: 'Strict public speech laws', value: 'Laws are strict about public speech; avoid criticizing the government or religion.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Avoid public affection', value: 'Public displays of affection should be avoided. Hand-holding is generally fine, but kissing is not appropriate.', type: 'dont' },
          { label: 'Tipping appreciated', value: 'While service charges are often included, additional tipping is appreciated. Round up taxi fares and tip hotel porters 10-20 AED.', type: 'tip' },
          { label: 'Respect Ramadan customs', value: 'During Ramadan, respect those fasting by avoiding eating, drinking, or smoking in public during daylight hours.', type: 'dont' },
          { label: 'Ask before photographing', value: 'Always ask for permission before photographing people, especially women in traditional dress.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free', value: 'Israeli passport holders can enter the UAE visa-free for up to 30 days since the Abraham Accords (2020). No prior arrangement needed.', type: 'do' },
      { label: 'US/EU — Visa on Arrival', value: 'US and EU citizens receive a free visa on arrival valid for 30 days, extendable once for another 30 days.', type: 'info' },
      { label: 'Passport Validity', value: 'Your passport must be valid for at least 6 months from your date of entry.', type: 'tip' },
      { label: 'No Israeli Stamps Issue', value: 'The UAE no longer refuses entry due to Israeli passport stamps since normalization in 2020.', type: 'info' },
    ],
  },
  'paris': {
    headline: 'Paris is a city of art, romance, and joie de vivre, constantly surprising visitors with its charm and everyday moments.',
    emoji: '🇫🇷',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respect Cathedrals', value: 'When visiting churches and cathedrals, dress modestly, covering shoulders and knees, and maintain a respectful silence.', type: 'do' },
          { label: 'Sunday Closures', value: 'Be aware that some smaller shops and businesses may be closed on Sundays, especially outside major tourist areas.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Comfortable Shoes', value: 'Comfortable walking shoes are essential as you\'ll likely be exploring the city on foot for extended periods.', type: 'do' },
          { label: 'Layered Clothing', value: 'Pack layers for changeable weather, as temperatures can fluctuate throughout the day, and a light rain jacket is advisable.', type: 'tip' },
          { label: 'Modest for Churches', value: 'When visiting religious sites like Notre Dame or Sacré-Cœur, wear modest clothing that covers your shoulders and knees.', type: 'do' },
          { label: 'Small Day Bag', value: 'Carry a small day bag for museums and daily excursions to keep your essentials secure and easily accessible.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Boulangerie Meals', value: 'Opt for a baguette sandwich, pastry, and coffee from a local boulangerie for a delicious and affordable meal, often better than tourist cafes.', type: 'do' },
          { label: 'Authentic Pastries', value: 'Always get your pastries from actual boulangeries, not random cafes, as the quality difference is significant.', type: 'tip' },
          { label: 'Ask for Tap Water', value: 'Paris tap water is safe and good to drink. Restaurants are legally required to provide free tap water (une carafe d\'eau) when you order food.', type: 'do' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Beware Pickpockets', value: 'While generally safe, pickpocketing can occur on tourist-heavy Métro lines (1, 4, 6) and at major stations. Keep bags zipped and valuables secure.', type: 'dont' },
          { label: 'Free Tap Water', value: 'By law, restaurants in France must provide free tap water (une carafe d\'eau) to customers who order food.', type: 'info' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Start with Bonjour', value: 'Always start interactions with \'Bonjour\' (good day) or \'Bonsoir\' (good evening) and attempt a few French phrases; it makes a big difference.', type: 'do' },
          { label: 'Montmartre Early', value: 'Visit Montmartre early in the morning before tour groups arrive to experience its beauty and walk around peacefully.', type: 'tip' },
          { label: 'Effort Changes Perception', value: 'The stereotype of Parisian rudeness often applies to those who don\'t make an effort; a simple \'Bonjour\' and attempt at French can change everything.', type: 'tip' },
          { label: 'Queue Politely', value: 'When waiting in line, whether for attractions or shops, form an orderly queue and wait your turn patiently.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (Schengen)', value: 'Israeli citizens can visit France and all Schengen countries for up to 90 days in any 180-day period without a visa.', type: 'do' },
      { label: 'US — Visa Free (90 days)', value: 'US citizens can stay in France for up to 90 days without a visa for tourism or business.', type: 'info' },
      { label: 'ETIAS from 2025', value: 'From 2025, non-EU visitors (including Israelis and Americans) will need to register for ETIAS (€7) before entering the Schengen Zone.', type: 'tip' },
      { label: 'Passport Validity', value: 'Passport must be valid for at least 3 months beyond your planned departure from the Schengen Area.', type: 'tip' },
    ],
  },
  'tokyo': {
    headline: 'Tokyo: A city where ancient traditions and futuristic innovation coexist, with a strong emphasis on quiet respect and meticulous etiquette.',
    emoji: '🇯🇵',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Shoes off indoors', value: 'Remove shoes when entering homes, temples, some restaurants, and traditional ryokan inns. Wear clean socks or bring indoor slippers.', type: 'do' },
          { label: 'Public bath etiquette', value: 'Wash thoroughly before entering communal baths (sento/onsen). Tattoos may lead to refusal in some establishments.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Tattoo visibility', value: 'Tattoos are taboo in public baths and some gyms; consider covering them or choosing tattoo-friendly establishments.', type: 'info' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'No eating while walking', value: 'Avoid eating while walking in public; finish your food at the point of purchase or a designated area.', type: 'dont' },
          { label: 'Chopstick etiquette', value: 'Never stick chopsticks vertically into rice or pass food from chopstick to chopstick, as these are associated with funeral rites.', type: 'dont' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Quiet on trains', value: 'Keep your phone on silent and conversations at a whisper on trains to avoid disturbing other passengers.', type: 'dont' },
          { label: 'Proper trash disposal', value: 'Carry your trash until you find a designated bin, which can be scarce. Convenience stores often have them.', type: 'do' },
          { label: 'Smoking rules', value: 'Smoking is banned on most streets; use designated smoking areas.', type: 'info' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Queue patiently', value: 'Always queue in lines; cutting in line is not acceptable and considered rude.', type: 'do' },
          { label: 'Escalator courtesy', value: 'Stand on the left side of escalators in Tokyo to allow others to pass on the right.', type: 'do' },
          { label: 'Learn basic phrases', value: 'Learning simple phrases like \'Sumimasen\' (excuse me/sorry/thank you) and \'Arigatou gozaimasu\' (thank you) is helpful and appreciated.', type: 'tip' },
          { label: 'Ask for help politely', value: 'Japanese people are generally very helpful if approached politely, so don\'t hesitate to ask for assistance.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free', value: 'Israeli passport holders can enter Japan visa-free for up to 90 days for tourism.', type: 'do' },
      { label: 'US/EU — Visa Free (90 days)', value: 'US and EU citizens can visit Japan for up to 90 days without a visa.', type: 'info' },
      { label: 'Visit Japan Web', value: 'Register on Visit Japan Web before arrival to speed up immigration and customs. It\'s free and saves significant time.', type: 'tip' },
      { label: 'No Work Allowed', value: 'Visa-free entry is for tourism only. Working without a proper visa is illegal and can result in deportation.', type: 'dont' },
    ],
  },
  'new-york': {
    headline: 'New York City offers a vibrant mix of world-class culture, diverse neighborhoods, iconic landmarks, and an unparalleled culinary scene.',
    emoji: '🇺🇸',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Tipping is expected', value: 'Tipping is not optional in the US; service workers depend on tips as part of their income.', type: 'info' },
          { label: 'Standard restaurant tips', value: 'Tip 18-20% of the pre-tax bill in restaurants.', type: 'do' },
          { label: 'Bar tipping etiquette', value: 'Tip $1-2 per drink, or 20% of the tab at bars.', type: 'do' },
          { label: 'Hotel staff gratuity', value: 'Tip hotel housekeeping $2-5 per night and porters $2-5 per bag.', type: 'do' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Comfortable walking shoes', value: 'Pack comfortable walking shoes as you will cover significant distances daily.', type: 'tip' },
          { label: 'Dress in layers', value: 'New York experiences four distinct seasons, so layered clothing is often advisable.', type: 'tip' },
          { label: 'Fashionable attire', value: 'New Yorkers often dress stylishly, especially for evenings out, so consider bringing some fashionable options.', type: 'info' },
          { label: 'Weather-appropriate clothing', value: 'Ensure your clothing is appropriate for the season you are visiting.', type: 'do' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Diverse culinary scene', value: 'New York boasts over 27,000 restaurants offering every global cuisine imaginable.', type: 'info' },
          { label: 'Eat like a local', value: 'Seek out local favorites like halal carts and dollar pizza, often found where lines are longest.', type: 'tip' },
          { label: 'Safe tap water', value: 'New York City tap water is safe to drink and of high quality; carry a reusable bottle.', type: 'info' },
          { label: 'Try dollar pizza', value: 'Experience a true New York staple by trying a $2 pizza slice that locals swear by.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Valid travel documents', value: 'Ensure you have a valid passport and ESTA authorization or appropriate visa before traveling.', type: 'do' },
          { label: 'Avoid renting a car', value: 'Do not rent a car; New York\'s public transport is efficient, and parking is expensive.', type: 'dont' },
          { label: 'Urban safety precautions', value: 'Keep valuables secure, avoid empty subway cars late at night, and stay in well-lit areas.', type: 'do' },
          { label: 'Tipping is mandatory', value: 'Tipping is expected and considered part of service workers\' income, not optional.', type: 'info' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Book accommodations early', value: 'Book your hotel 6-8 weeks in advance, especially during peak seasons (April-November and December holidays).', type: 'tip' },
          { label: 'Download essential apps', value: 'Install Google Maps, Citymapper, Yelp, The New York Times, and OpenTable before arrival.', type: 'tip' },
          { label: 'Walk and explore', value: 'Walk more than you plan; many discoveries happen unexpectedly between destinations.', type: 'tip' },
          { label: 'Be aware of surroundings', value: 'Always be mindful of your environment, especially in crowded areas or at night.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — ESTA Required', value: 'Israeli citizens must apply for ESTA (Electronic System for Travel Authorization) before traveling to the US. Cost: $21, valid 2 years.', type: 'info' },
      { label: 'EU — ESTA Required', value: 'EU citizens also need ESTA for visits up to 90 days under the Visa Waiver Program. Apply at esta.cbp.dhs.gov.', type: 'info' },
      { label: 'Apply Early', value: 'Apply for ESTA at least 72 hours before departure. Most approvals are instant but some take longer.', type: 'tip' },
      { label: 'CBP Declaration', value: 'All visitors must complete a CBP Declaration Form on arrival. Declare all food, plants, and amounts over $10,000 in cash.', type: 'do' },
    ],
  },
  'london': {
    headline: 'London is a vibrant, multicultural hub where tradition meets modernity, offering a rich tapestry of history, arts, and diverse communities.',
    emoji: '🇬🇧',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Christianity dominant', value: 'While predominantly Christian, London is a melting pot of religions, with significant Muslim, Hindu, Sikh, Jewish, and Buddhist communities. Respect all religious practices and places of worship.', type: 'info' },
          { label: 'Religious tolerance', value: 'Londoners generally embrace religious diversity. Be open-minded and respectful of different beliefs and customs.', type: 'do' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Layered clothing', value: 'London weather can be unpredictable, so dressing in layers is advisable. Be prepared for rain at any time of year.', type: 'tip' },
          { label: 'Smart casual for evenings', value: 'For dining out or theatre, smart casual attire is generally appropriate. Some upscale establishments may require more formal wear.', type: 'tip' },
          { label: 'Comfortable shoes', value: 'You\'ll likely do a lot of walking, so comfortable footwear is essential for exploring the city.', type: 'do' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Try traditional pubs', value: 'Experience classic British pub culture, offering traditional food like fish and chips, and a wide selection of beers and ales.', type: 'do' },
          { label: 'Explore diverse cuisines', value: 'London boasts an incredible array of international cuisines. Don\'t hesitate to explore different neighborhoods for authentic culinary experiences.', type: 'do' },
          { label: 'Tipping etiquette', value: 'A service charge of 10-12.5% is often added to restaurant bills. If not, a similar amount is customary for good service.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'No smoking indoors', value: 'Smoking is prohibited in all enclosed public spaces, including pubs, restaurants, and workplaces.', type: 'dont' },
          { label: 'Public drinking restrictions', value: 'While generally allowed, some public transport and specific areas have restrictions on drinking alcohol. Always check local signage.', type: 'info' },
          { label: 'Drug laws strictly enforced', value: 'Possession and use of illegal drugs are strictly prohibited and carry severe penalties.', type: 'dont' },
          { label: 'Littering fines', value: 'Dropping litter in public places can result in a fine. Use designated bins.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Queue patiently', value: 'Queuing is a fundamental part of British culture. Wait your turn patiently in lines for buses, shops, and attractions.', type: 'do' },
          { label: 'Mind the gap', value: 'When using the London Underground, pay attention to the \'mind the gap\' announcement and be cautious when boarding and alighting trains.', type: 'tip' },
          { label: 'Stand on the right', value: 'On escalators, stand on the right to allow others to walk on the left.', type: 'do' },
          { label: 'Polite greetings', value: 'A simple \'please\' and \'thank you\' go a long way in daily interactions.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — eTA Required (2025)', value: 'From 2025, Israeli citizens need a UK Electronic Travel Authorisation (ETA) to visit the UK. Cost: £10, valid 2 years.', type: 'info' },
      { label: 'US/EU — ETA Required (2025)', value: 'US and EU citizens also need the UK ETA from 2025. Apply via the UK ETA app or gov.uk website.', type: 'info' },
      { label: 'No Schengen Link', value: 'The UK is NOT part of the Schengen Area. A Schengen visa does not allow entry to the UK — you need a separate UK visa/ETA.', type: 'dont' },
      { label: 'Passport Validity', value: 'Your passport must be valid for the entire duration of your stay in the UK.', type: 'tip' },
    ],
  },
  'barcelona': {
    headline: 'Barcelona blends Gaudí\'s fantastical architecture with Mediterranean beaches, Gothic alleyways, and one of Europe\'s most vibrant food scenes.',
    emoji: '🇪🇸',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Catalan Culture', value: 'Catalonia\'s capital has a fierce identity, with Catalan as the primary language and a pride in local traditions like human tower festivals.', type: 'info' },
          { label: 'Local Rhythms', value: 'Embrace the local schedule: lunch from 2 PM to 4 PM, dinner starting at 9 PM, and vermouth hour around 7 PM.', type: 'do' },
          { label: 'Siesta Time', value: 'Barcelona still values afternoons for rest, so expect some shops and businesses to be closed between 2-5 PM.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Dress in Layers', value: 'Pack layers as mornings can be cool, afternoons warm, and air conditioning aggressive indoors.', type: 'tip' },
          { label: 'Comfortable Shoes', value: 'Wear comfortable shoes for walking, especially in the Gothic Quarter where streets are car-free and walking is often faster than metro.', type: 'tip' },
          { label: 'Beachwear', value: 'Beachwear is acceptable at Barceloneta Beach, but dress modestly when visiting religious sites or upscale restaurants.', type: 'info' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Try Local Dishes', value: 'Sample paella, patatas bravas, crema catalana, jamón ibérico, and pan con tomate for authentic Catalan flavors.', type: 'do' },
          { label: 'Avoid La Rambla', value: 'Don\'t eat at restaurants directly on La Rambla, as they are often overpriced and offer poor quality food.', type: 'dont' },
          { label: 'Explore Side Streets', value: 'Walk one or two blocks off La Rambla for better food options at more reasonable prices.', type: 'tip' },
          { label: 'Late Dining', value: 'Dinner typically starts around 9 PM or 10 PM; arriving earlier might mean limited options or an empty restaurant.', type: 'info' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Guard Valuables', value: 'Be vigilant against pickpocketing, especially in crowded areas like La Rambla and public transport. Keep valuables secure and out of sight.', type: 'do' },
          { label: 'Avoid Driving in Old City', value: 'Do not attempt to drive in the old city areas like the Gothic Quarter, as streets are narrow and often pedestrian-only.', type: 'dont' },
          { label: 'Buy Official Tickets', value: 'Always purchase tickets for attractions from official sellers to avoid scams and unofficial vendors.', type: 'do' },
          { label: 'No Flashing Valuables', value: 'Avoid flashing expensive jewelry or phones in crowded tourist areas to minimize the risk of theft.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Learn Basic Phrases', value: 'Learning a few basic phrases in Spanish or Catalan can enhance your experience and show respect to locals.', type: 'tip' },
          { label: 'Book Attractions Ahead', value: 'Book tickets for popular attractions like Sagrada Familia and Park Güell weeks in advance, especially during peak season, as they sell out quickly.', type: 'do' },
          { label: 'Visit Gaudí Sites Early/Late', value: 'To avoid overwhelming crowds, visit Gaudí sites early in the morning or late in the afternoon.', type: 'tip' },
          { label: 'Embrace Slow Pace', value: 'Barcelona rewards those who go slow. Wander through neighborhoods, sit in a plaza, and observe local life to truly experience the city.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (Schengen)', value: 'Israeli citizens can visit Spain and all Schengen countries for up to 90 days in any 180-day period without a visa.', type: 'do' },
      { label: 'US — Visa Free (90 days)', value: 'US citizens can stay in Spain for up to 90 days without a visa for tourism.', type: 'info' },
      { label: 'ETIAS from 2025', value: 'From 2025, non-EU visitors will need ETIAS registration (€7) before entering Schengen. Apply online in advance.', type: 'tip' },
      { label: 'Tourist Tax', value: 'Barcelona charges a tourist tax of €3.25–€6.75 per night depending on accommodation type. Pay at check-in.', type: 'info' },
    ],
  },
  'singapore': {
    headline: 'Singapore is a vibrant city-state known for its harmonious blend of cultures, strict laws, and a passion for food.',
    emoji: '🇸🇬',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Religious Harmony', value: 'Singapore embraces a multitude of religions, including Buddhism, Islam, Christianity, and Hinduism. Respect all places of worship and remove your shoes before entering temples or mosques.', type: 'info' },
          { label: 'Observe Festivals', value: 'Many religious festivals are celebrated throughout the year. Be mindful of local customs and traditions during these times.', type: 'tip' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Modest Attire', value: 'While generally modern, dress modestly when visiting religious sites to show respect. Shoulders and knees should be covered.', type: 'do' },
          { label: 'Light Clothing', value: 'Singapore\'s tropical climate calls for light, breathable fabrics like cotton or linen. Pack comfortable shoes for walking.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Hawker Centre Etiquette', value: 'Hawker centres are a culinary highlight. \'Chop\' your table with tissue packets to reserve it while you order, but don\'t linger too long after eating.', type: 'do' },
          { label: 'No Durian on Public Transport', value: 'The pungent durian fruit is banned on public transport and in many hotels. Be aware of signs.', type: 'dont' },
          { label: 'Try Local Delicacies', value: 'Don\'t miss out on chili crab, laksa, and Hainanese chicken rice. Explore the diverse culinary scene.', type: 'do' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Chewing Gum Ban', value: 'The import and sale of chewing gum is prohibited, with exceptions for therapeutic gum. Spitting gum is also illegal.', type: 'dont' },
          { label: 'No Littering', value: 'Singapore has very strict anti-littering laws. Fines are hefty, so always dispose of your trash properly.', type: 'dont' },
          { label: 'Drug Trafficking', value: 'Drug offenses carry severe penalties, including the death sentence. Do not engage in any drug-related activities.', type: 'dont' },
          { label: 'Vandalism Penalties', value: 'Vandalism, including graffiti, is taken very seriously and can result in caning and imprisonment.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Queue Up', value: 'Queuing is a common practice in Singapore. Always wait your turn patiently, whether for food, transport, or attractions.', type: 'do' },
          { label: 'Respect Elders', value: 'Show respect to elders and those in positions of authority. Use polite language and gestures.', type: 'do' },
          { label: 'Tipping Not Customary', value: 'Tipping is not generally expected in Singapore as a service charge is often included in bills.', type: 'info' },
          { label: 'Remove Shoes Indoors', value: 'It is customary to remove your shoes before entering someone\'s home or certain religious establishments.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (30 days)', value: 'Israeli passport holders can enter Singapore visa-free for up to 30 days for tourism.', type: 'do' },
      { label: 'US/EU — Visa Free (30 days)', value: 'US and EU citizens can visit Singapore for up to 30 days without a visa.', type: 'info' },
      { label: 'SG Arrival Card', value: 'All visitors must complete the Singapore Arrival Card (SGAC) within 3 days before arrival. It\'s free at eservices.ica.gov.sg.', type: 'tip' },
      { label: 'Extension Available', value: 'You can extend your stay at the ICA Building in Singapore for up to 30 additional days if needed.', type: 'info' },
    ],
  },
  'bangkok': {
    headline: 'Bangkok pulses as Southeast Asia\'s spiritual and sensory capital, where gilded temple spires pierce humid skies, street vendors serve Michelin-starred pad thai for 60 THB ($1.70), and ancient traditions thrive alongside rooftop infinity pools.',
    emoji: '🇹🇭',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Remove Shoes', value: 'Always remove your shoes when entering homes and temples as a sign of respect.', type: 'do' },
          { label: 'Respect Head & Feet', value: 'Never touch anyone\'s head, as it\'s considered the most sacred part of the body. Avoid pointing your feet at people or Buddha images, as feet are considered the lowest and dirtiest part.', type: 'dont' },
          { label: 'Return Wai Greeting', value: 'A polite \'wai\' (palms pressed together, slight bow) is a common and respectful greeting in Thailand. Return it when offered.', type: 'do' },
          { label: 'Deference to Monks', value: 'Monks hold the highest status in Thai society. Give them space and show deference, especially women who should avoid direct physical contact.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Temple Dress Code', value: 'When visiting temples, ensure you wear long pants, covered shoulders, and closed shoes. The dress code is strictly enforced, and you may be turned away for inappropriate attire.', type: 'info' },
          { label: 'Pack Modest Clothing', value: 'Pack modest clothing for temple visits and light layers for air-conditioned indoor spaces, which can be quite cold.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Explore Street Food', value: 'Bangkok\'s street food scene is legendary. Don\'t be afraid to try various vendors; you can find Michelin-starred quality meals for just a few dollars.', type: 'do' },
          { label: 'Must-Try Dishes', value: 'Sample iconic Thai dishes like pad thai, tom yum goong (spicy shrimp soup), and som tam (green papaya salad). Local markets are ideal for authentic flavors.', type: 'info' },
          { label: 'Jay Fai\'s Crab Omelet', value: 'For a unique culinary experience, try Jay Fai\'s Michelin-starred crab omelet. Be prepared to reserve weeks ahead or queue for hours, but many travelers find it worth the wait.', type: 'tip' },
          { label: 'Drink Local Beer', value: 'Enjoy local beers like Chang and Singha, which are readily available and more affordable at convenience stores than in bars.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Respect Royal Family', value: 'It is crucial to show utmost respect for the Thai royal family. Lese-majesty laws are strict, and any perceived disrespect can lead to severe penalties.', type: 'dont' },
          { label: 'No Public Anger', value: 'Public displays of anger or losing your temper are considered deeply embarrassing in Thai culture. Always try to maintain a calm demeanor.', type: 'dont' },
          { label: 'Insist on Meter', value: 'When taking a taxi, always insist that the driver uses the meter. If they refuse, find another taxi, as there are many available.', type: 'do' },
          { label: 'Tuk-Tuk Scams', value: 'Be wary of tuk-tuk drivers offering unusually cheap rides that include stops at gem shops or tailor stores; these are often scams where drivers earn commission.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Carry Cash', value: 'Always carry cash for street food vendors and small shops, as many do not accept card payments.', type: 'tip' },
          { label: 'Download Grab & Maps', value: 'Download the Grab ride-hailing app and Google Maps (for offline use) before your arrival to help with navigation and transportation.', type: 'tip' },
          { label: 'Book Grand Palace Early', value: 'Visit the Grand Palace early in the morning to avoid large crowds and the intense heat, ensuring a more pleasant experience.', type: 'tip' },
          { label: 'Embrace the Chaos', value: 'Bangkok can be overwhelming, but its unique charm lies in its vibrant chaos. Embrace the experience and allow for spontaneous exploration.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa on Arrival', value: 'Israeli citizens can get a visa on arrival in Thailand for 30 days (fee: ~1,000 THB ≈ $27). Or apply for an e-Visa in advance.', type: 'info' },
      { label: 'US/EU — Visa Exemption', value: 'US and EU citizens get 30-day visa exemption on arrival. Extended to 60 days for some nationalities from 2024.', type: 'do' },
      { label: 'Thailand e-Visa', value: 'Apply for a Thailand e-Visa online before travel to avoid queues at the airport. Available at thaievisa.go.th.', type: 'tip' },
      { label: 'Overstay Penalties', value: 'Overstaying your visa in Thailand results in a fine of 500 THB per day and possible blacklisting. Leave on time.', type: 'dont' },
    ],
  },
  'rome': {
    headline: 'Rome layers 2,800 years of history across seven hills, blending ancient ruins with Renaissance masterpieces and modern Italian life.',
    emoji: '🇮🇹',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Embrace Roman Tempo', value: 'Romans operate on a different tempo than Northern Europeans or Americans. Lunch stretches for two hours. Shops close from 13:00 to 16:30 for riposo. Dinner doesn\'t start until 20:00 at the earliest. Embrace this rhythm to avoid exhaustion.', type: 'do' },
          { label: 'Easter Crowds', value: 'Easter brings massive crowds to Vatican City. Plan accordingly or avoid visiting the Vatican during this period.', type: 'info' },
          { label: 'Ferragosto Closures', value: 'Many Romans abandon the city for August\'s Ferragosto holiday (August 15), causing restaurants, shops, and even some hotels to close.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Church Dress Code', value: 'When visiting major churches like St. Peter\'s, Santa Maria Maggiore, and San Giovanni in Laterano, ensure your shoulders and knees are covered. Avoid flip-flops or beachwear as entry may be denied.', type: 'do' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Authentic Roman Cuisine', value: 'Rome\'s cuisine focuses on simple, perfectly prepared dishes like cacio e pepe, carbonara, amatriciana, and saltimbocca. Seek out neighborhood trattorias for better quality and prices.', type: 'info' },
          { label: 'Coffee Etiquette', value: 'Drink coffee standing at the bar to pay local prices (€1-1.50). Sitting at a table can double or triple the cost.', type: 'do' },
          { label: 'No Cappuccino After Lunch', value: 'Ordering a cappuccino after lunch is a clear sign of a tourist. Romans consider milk-based coffee a breakfast drink only.', type: 'dont' },
          { label: 'Spot Good Trattorias', value: 'Look for trattorias with menus primarily in Italian, locals dining there, no one soliciting outside, handwritten specials, and a small, focused menu to avoid tourist traps.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'No Indoor Smoking', value: 'Smoking is prohibited in all indoor public places, including restaurants, bars, and public transportation.', type: 'dont' },
          { label: 'Public Drinking', value: 'Drinking alcohol in public spaces is generally allowed, but public intoxication is frowned upon and can lead to fines.', type: 'info' },
          { label: 'Use Crosswalks', value: 'While jaywalking is common, it is technically illegal. Use designated crosswalks for safety and to avoid potential fines.', type: 'do' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Wander and Explore', value: 'Rome rewards those who wander. Spend time getting lost in backstreets like Trastevere and discover hidden gems rather than rushing between major museums.', type: 'tip' },
          { label: 'Wear Sturdy Shoes', value: 'Cobblestone streets are beautiful but can be hard on your feet. Wear sturdy shoes with good support for comfortable walking.', type: 'do' },
          { label: 'Beware of Pickpockets', value: 'Be vigilant for pickpockets, especially on crowded public transport (like the 64 bus) and around popular tourist attractions.', type: 'dont' },
          { label: 'Respect Local Pace', value: 'Embrace the Roman pace of life, including long lunches and late dinners. Fighting this rhythm will lead to exhaustion.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (Schengen)', value: 'Israeli citizens can visit Italy and all Schengen countries for up to 90 days in any 180-day period without a visa.', type: 'do' },
      { label: 'US — Visa Free (90 days)', value: 'US citizens can stay in Italy for up to 90 days without a visa for tourism.', type: 'info' },
      { label: 'ETIAS from 2025', value: 'From 2025, non-EU visitors will need ETIAS (€7) before entering Schengen. Apply online at etias.com.', type: 'tip' },
      { label: 'Vatican Entry', value: 'Vatican City is a separate country. No additional visa is needed for tourists already in Italy.', type: 'info' },
    ],
  },
  'istanbul': {
    headline: 'Istanbul is a vibrant city where East meets West, offering a rich tapestry of history, culture, and modern life.',
    emoji: '🇹🇷',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respect Mosques', value: 'When visiting mosques, dress modestly, covering shoulders and knees. Women should cover their heads. Remove shoes before entering.', type: 'do' },
          { label: 'Call to Prayer', value: 'Be aware of the five daily calls to prayer (ezan) which are broadcast from mosques and can be heard throughout the city.', type: 'info' },
          { label: 'Ramadan Fasting', value: 'During the holy month of Ramadan, many Muslims fast from dawn till dusk. Be mindful and respectful of those fasting.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Modest Attire', value: 'Dress modestly, especially when visiting religious sites. Shoulders and knees should be covered. For women, a headscarf is often required for mosques.', type: 'do' },
          { label: 'Comfortable Shoes', value: 'Istanbul involves a lot of walking on uneven surfaces, so comfortable footwear is essential.', type: 'tip' },
          { label: 'Layered Clothing', value: 'Weather can change quickly, so dressing in layers is advisable for comfort throughout the day.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Try Local Cuisine', value: 'Indulge in traditional Turkish dishes like kebabs, baklava, Turkish delight, and simit. Don\'t miss the street food.', type: 'do' },
          { label: 'Raki Etiquette', value: 'Raki, an anise-flavored alcoholic drink, is often consumed with meze. It\'s typically mixed with water and ice, turning cloudy.', type: 'info' },
          { label: 'Don\'t Waste Food', value: 'It\'s considered impolite to waste food. Order what you can finish.', type: 'dont' },
          { label: 'Tea Culture', value: 'Tea (çay) is a significant part of Turkish culture and hospitality. Accept offers of tea from shopkeepers or hosts.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Alcohol Consumption', value: 'While alcohol is available, public consumption in certain areas may be frowned upon. Be discreet and respectful.', type: 'info' },
          { label: 'Smoking Laws', value: 'Smoking is prohibited in all indoor public places, including restaurants, bars, and cafes.', type: 'info' },
          { label: 'Photography Rules', value: 'Always ask for permission before taking photos of people, especially women. Be respectful of privacy.', type: 'tip' },
          { label: 'Drug Laws', value: 'Turkey has strict laws against drug possession and trafficking, with severe penalties.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Bargaining in Bazaars', value: 'Haggling is common and expected in markets like the Grand Bazaar. Start with a lower offer and negotiate politely.', type: 'tip' },
          { label: 'Greetings', value: 'A handshake is a common greeting. For elders, it\'s customary to kiss their right hand and then bring it to your forehead as a sign of respect.', type: 'info' },
          { label: 'Remove Shoes Indoors', value: 'It is customary to remove your shoes before entering a private home or a mosque.', type: 'do' },
          { label: 'Hospitality', value: 'Turks are known for their hospitality. Accepting an offer of tea or a small treat is a sign of appreciation.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — e-Visa Required', value: 'Israeli citizens must obtain a Turkish e-Visa before arrival. Cost: $50, valid 180 days, allows 90-day stay. Apply at evisa.gov.tr.', type: 'info' },
      { label: 'US/EU — e-Visa Required', value: 'US and EU citizens also need a Turkish e-Visa ($50). Apply online at evisa.gov.tr at least 48 hours before travel.', type: 'info' },
      { label: 'Apply in Advance', value: 'Do not wait until the airport — apply for your e-Visa at least 48 hours before departure to avoid issues.', type: 'tip' },
      { label: 'Passport Validity', value: 'Your passport must be valid for at least 6 months beyond your planned departure from Turkey.', type: 'tip' },
    ],
  },
  'amsterdam': {
    headline: 'Amsterdam is a vibrant city known for its artistic heritage, elaborate canal system, and cycling culture.',
    emoji: '🇳🇱',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Religious Tolerance', value: 'The Netherlands is a secular country with a strong tradition of religious tolerance. While Christianity is the largest religion, a significant portion of the population is irreligious, and diverse faiths coexist peacefully.', type: 'info' },
          { label: 'No Strict Observance', value: 'There are no strict religious observances expected from visitors. Respect local customs during religious holidays, but generally, public life is not heavily influenced by religious practices.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Casual & Comfortable', value: 'Dress in Amsterdam is generally casual and comfortable. Layers are recommended due to changeable weather. Practical footwear is essential for walking and cycling.', type: 'tip' },
          { label: 'Modesty in Churches', value: 'When visiting churches or other religious sites, it\'s respectful to dress modestly, covering shoulders and knees, although this is not strictly enforced in all places.', type: 'do' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Try Local Delicacies', value: 'Don\'t miss out on Dutch specialties like stroopwafels, herring, bitterballen, and various cheeses. Explore local markets for fresh produce and snacks.', type: 'do' },
          { label: 'Tipping Etiquette', value: 'Tipping is not mandatory but appreciated for good service. A 5-10% tip is common in restaurants if you\'re satisfied, or simply rounding up the bill.', type: 'tip' },
          { label: 'Coffee Shop Culture', value: 'Be aware that \'coffee shops\' in Amsterdam sell cannabis, not just coffee. If you\'re looking for a regular cafe, ask for a \'koffiehuis\' or \'cafe\'.', type: 'info' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Soft Drugs Policy', value: 'While cannabis is tolerated in designated coffee shops, it is not legal. Public use outside these establishments is prohibited, and hard drugs are illegal.', type: 'info' },
          { label: 'Cycling Rules', value: 'Amsterdam is a cycling city. Always follow traffic rules, use hand signals, and be aware of pedestrians. Cycling under the influence is illegal.', type: 'do' },
          { label: 'Public Drinking', value: 'Drinking alcohol in public spaces is generally prohibited in many areas, especially in the city center. Consume alcohol in licensed establishments.', type: 'dont' },
          { label: 'No Littering', value: 'Keep the city clean. Fines can be issued for littering. Use public bins or take your rubbish with you.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Respect Cyclists', value: 'Be mindful of cyclists; they have right of way in many situations. Avoid walking in bike lanes.', type: 'do' },
          { label: 'Punctuality', value: 'Punctuality is generally valued in social and business settings. Arriving on time is a sign of respect.', type: 'do' },
          { label: 'Direct Communication', value: 'Dutch communication is often direct and to the point. This is not considered rude but rather efficient.', type: 'info' },
          { label: 'Queueing', value: 'Wait your turn in lines and queues. Cutting in line is considered impolite.', type: 'dont' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (Schengen)', value: 'Israeli citizens can visit the Netherlands and all Schengen countries for up to 90 days in any 180-day period without a visa.', type: 'do' },
      { label: 'US — Visa Free (90 days)', value: 'US citizens can stay in the Netherlands for up to 90 days without a visa.', type: 'info' },
      { label: 'ETIAS from 2025', value: 'From 2025, non-EU visitors will need ETIAS (€7) before entering Schengen. Apply online before travel.', type: 'tip' },
      { label: 'Tourist Tax', value: 'Amsterdam charges a tourist tax of 12.5% on accommodation costs. This is usually included in your booking price.', type: 'info' },
    ],
  },
  'miami': {
    headline: 'Where Latin Soul Meets Ocean Breeze',
    emoji: '🇺🇸',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Bilingual Culture', value: 'Many locals in Miami are bilingual, often switching between English and Spanish in conversation. Learning a few Spanish phrases can be helpful.', type: 'info' },
          { label: 'Cuban Influence', value: 'Miami has a strong Cuban cultural presence, especially in areas like Little Havana, where domino games and traditional vendors are common.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Casual & Stylish', value: 'Miami\'s climate is warm, so light, breathable clothing is recommended. Dress tends to be casual but stylish, especially in popular areas like South Beach.', type: 'tip' },
          { label: 'Beachwear Appropriate', value: 'Beachwear is common near coastal areas, but it\'s advisable to cover up when entering establishments or moving away from the immediate beach.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Try Cuban Coffee', value: 'Experience Miami\'s vibrant coffee culture by trying a \'cortadito\' or \'cafecito\' from a local \'ventanita\'.', type: 'do' },
          { label: 'Explore Food Trucks', value: 'Miami\'s diverse food scene includes numerous food trucks offering everything from Latin American to American cuisine. They are often a budget-friendly option.', type: 'tip' },
          { label: 'Taste Croquetas', value: 'Don\'t miss out on trying croquetas, a popular Cuban snack, often found at local vendors in areas like Little Havana.', type: 'do' },
          { label: 'Diverse Culinary Scene', value: 'Miami offers a wide range of dining experiences, from upscale restaurants to casual eateries and food trucks, reflecting its multicultural population.', type: 'info' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Drinking Age 21', value: 'The legal drinking age in Miami, as in all of the United States, is 21. Be prepared to show identification.', type: 'info' },
          { label: 'Public Alcohol Consumption', value: 'Public consumption of alcohol outside of designated areas is generally prohibited. Always check local regulations.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Tipping Customary', value: 'Tipping is customary in the United States. A tip of 15-20% for good service in restaurants and for other services is expected.', type: 'tip' },
          { label: 'Be Budget Conscious', value: 'Miami can be expensive, especially in tourist hotspots. Consider eating at food trucks or staying inland to save money.', type: 'tip' },
          { label: 'Embrace the Vibe', value: 'Miami has a unique, energetic atmosphere. Be open to experiencing its Latin-infused culture and vibrant nightlife.', type: 'tip' },
          { label: 'Weather Preparedness', value: 'Be prepared for warm weather year-round. Even in winter, temperatures are mild, but summer brings significant heat and humidity.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — ESTA Required', value: 'Israeli citizens must apply for ESTA before traveling to the US. Cost: $21, valid 2 years, allows multiple 90-day visits.', type: 'info' },
      { label: 'EU — ESTA Required', value: 'EU citizens need ESTA for visits up to 90 days under the Visa Waiver Program. Apply at esta.cbp.dhs.gov.', type: 'info' },
      { label: 'Apply Early', value: 'Apply for ESTA at least 72 hours before departure. Most approvals are instant but some take up to 72 hours.', type: 'tip' },
      { label: 'State Tax', value: 'Florida has no state income tax, but sales tax of 6–8% applies to most purchases. Hotel taxes are typically 12–13%.', type: 'info' },
    ],
  },
  'las-vegas': {
    headline: 'Las Vegas: The Entertainment Capital Where Every Night Is Legendary',
    emoji: '🇺🇸',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respect local culture', value: 'While Las Vegas is known for its liberal atmosphere, showing respect for diverse backgrounds and beliefs is always appreciated.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Casual daytime wear', value: 'During the day, comfortable and casual attire like shorts, t-shirts, and walking shoes are appropriate for exploring.', type: 'info' },
          { label: 'Restaurant dress codes', value: 'Many nicer restaurants enforce dress codes, so avoid shorts and flip-flops for evening dining.', type: 'dont' },
          { label: 'Nightclub attire', value: 'For nightclubs, men should wear dress shoes and collared shirts, while women often opt for designer wear.', type: 'do' },
          { label: 'Pack layers', value: 'Even though the desert is hot, casinos are heavily air-conditioned, so packing layers is advisable to stay comfortable.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'World-class dining', value: 'Las Vegas boasts a world-class dining scene with celebrity chefs and diverse culinary options beyond traditional buffets.', type: 'info' },
          { label: 'Modern buffets', value: 'While many buffets closed, some upscale options like Bacchanal and Wicked Spoon still offer quality dining experiences.', type: 'info' },
          { label: 'Free casino drinks', value: 'Drinks are often free while actively gambling, but service can be slow and tipping is expected ($1-2 per drink).', type: 'tip' },
          { label: 'Hydrate constantly', value: 'The dry desert climate can lead to rapid dehydration, so drink water frequently throughout the day.', type: 'do' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Legal gambling age', value: 'You must be 21 years old to gamble, drink alcohol, or enter most nightclubs and pool parties; ID is strictly enforced.', type: 'do' },
          { label: 'Public intoxication', value: 'While alcohol is prevalent, public intoxication can lead to legal issues. Drink responsibly.', type: 'dont' },
          { label: 'Marijuana laws', value: 'Recreational marijuana is legal for adults 21+, but consumption in public places, including casinos and hotels, is prohibited.', type: 'info' },
          { label: 'Street vendors', value: 'Avoid purchasing drugs or services from unauthorized street promoters to ensure your safety and avoid legal trouble.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Tipping is expected', value: 'Tipping is a significant part of the service culture; expect to tip 15-20% at restaurants and $1-2 per drink.', type: 'do' },
          { label: 'Casino etiquette', value: 'When gambling, be mindful of others at the table, wait for breaks in play to join, and avoid touching cards or chips until appropriate.', type: 'tip' },
          { label: 'Respect personal space', value: 'Despite the crowds, try to maintain a reasonable personal space, especially in queues and crowded areas.', type: 'info' },
          { label: 'Budget for gambling', value: 'Set a strict budget for gambling and stick to it; the house always has an advantage in the long run.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — ESTA Required', value: 'Israeli citizens must apply for ESTA before traveling to the US. Cost: $21, valid 2 years.', type: 'info' },
      { label: 'EU — ESTA Required', value: 'EU citizens need ESTA for visits up to 90 days under the Visa Waiver Program.', type: 'info' },
      { label: 'Nevada Resort Fees', value: 'Most Las Vegas hotels charge mandatory resort fees ($30–$50/night) not included in the advertised room rate.', type: 'tip' },
      { label: 'Gambling Age', value: 'The legal gambling age in Nevada is 21. ID is strictly checked at all casinos. Minors cannot even walk through casino floors.', type: 'info' },
    ],
  },
  'los-angeles': {
    headline: 'Los Angeles: A vibrant hub of entertainment, diverse cultures, and a laid-back, trendsetting lifestyle.',
    emoji: '🇺🇸',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Diverse Faiths', value: 'Los Angeles is a melting pot of cultures and religions. Respect all faiths and practices, as you\'ll encounter a wide array of beliefs.', type: 'info' },
          { label: 'Open-mindedness', value: 'Angelenos are generally open-minded and accepting of different lifestyles. Embrace the diversity and be respectful of individual choices.', type: 'tip' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Casual Chic', value: 'The dress code in Los Angeles is generally casual and comfortable, but with a touch of style. Think trendy streetwear, activewear, or relaxed bohemian looks.', type: 'info' },
          { label: 'Layer Up', value: 'Even on sunny days, evenings can get cool, especially near the coast. Always carry a light jacket or sweater for layering.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Diverse Cuisine', value: 'Los Angeles boasts an incredibly diverse culinary scene, from food trucks to Michelin-starred restaurants. Be adventurous and try different ethnic foods.', type: 'do' },
          { label: 'Tipping Etiquette', value: 'Tipping is customary in the US. Expect to tip 15-20% for good service at restaurants and bars.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Cannabis Laws', value: 'Recreational cannabis is legal for adults 21 and over, but consumption in public places is prohibited.', type: 'info' },
          { label: 'Drinking Age', value: 'The legal drinking age in California is 21. Be prepared to show ID.', type: 'info' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Traffic Patience', value: 'Los Angeles is known for its heavy traffic. Allow ample travel time and be patient, especially during rush hour.', type: 'tip' },
          { label: 'Car-centric City', value: 'While public transport exists, Los Angeles is largely a car-centric city. Renting a car is often the most convenient way to explore.', type: 'tip' },
          { label: 'Hollywood Glamour', value: 'Embrace the city\'s connection to the entertainment industry. You might spot celebrities, but respect their privacy.', type: 'info' },
          { label: 'Beach Culture', value: 'Enjoy the vibrant beach culture, but be mindful of local regulations regarding bonfires, alcohol, and noise.', type: 'do' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — ESTA Required', value: 'Israeli citizens must apply for ESTA before traveling to the US. Cost: $21, valid 2 years.', type: 'info' },
      { label: 'EU — ESTA Required', value: 'EU citizens need ESTA for visits up to 90 days under the Visa Waiver Program.', type: 'info' },
      { label: 'CBP Declaration', value: 'Declare all food, plants, and cash over $10,000 on your CBP Declaration Form on arrival at LAX.', type: 'do' },
      { label: 'California Sales Tax', value: 'California has a base sales tax of 7.25%, with LA County adding up to 10.25% total. Hotel taxes are typically 15–16%.', type: 'info' },
    ],
  },
  'hong-kong': {
    headline: 'Hong Kong is a vibrant fusion of East and West, where ancient traditions meet modern dynamism.',
    emoji: '🇭🇰',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respect Temples', value: 'When visiting temples, dress modestly and remove your shoes before entering.', type: 'do' },
          { label: 'Ancestral Worship', value: 'Many Hong Kongers practice ancestral worship, especially during festivals.', type: 'info' },
          { label: 'Feng Shui Importance', value: 'Feng Shui plays a significant role in architecture and daily life.', type: 'info' },
          { label: 'Lucky Numbers', value: 'Numbers like 8 are considered lucky, while 4 is unlucky.', type: 'info' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Casual Wear', value: 'Casual attire is generally acceptable for sightseeing and daily activities.', type: 'info' },
          { label: 'Modest for Temples', value: 'Dress modestly when visiting religious sites.', type: 'do' },
          { label: 'Business Attire', value: 'Business settings require formal attire.', type: 'info' },
          { label: 'Comfortable Shoes', value: 'Wear comfortable shoes for walking and exploring.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Dim Sum Etiquette', value: 'Share dishes and use chopsticks. Don\'t stick chopsticks upright in rice.', type: 'do' },
          { label: 'Try Street Food', value: 'Explore local street food stalls for authentic flavors.', type: 'do' },
          { label: 'No Tipping', value: 'Tipping is not customary in most local restaurants.', type: 'dont' },
          { label: 'Tea Culture', value: 'Tea is an integral part of meals and social gatherings.', type: 'info' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'No Littering', value: 'Littering is strictly prohibited and can result in heavy fines.', type: 'dont' },
          { label: 'Smoking Bans', value: 'Smoking is banned in most indoor public places and some outdoor areas.', type: 'dont' },
          { label: 'Public Order', value: 'Maintain public order and avoid disruptive behavior.', type: 'do' },
          { label: 'Drug Laws', value: 'Hong Kong has very strict drug laws with severe penalties.', type: 'dont' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Politeness', value: 'Be polite and respectful, especially to elders.', type: 'do' },
          { label: 'Queueing', value: 'Queue patiently for public transport and services.', type: 'do' },
          { label: 'Personal Space', value: 'Personal space is limited in crowded areas.', type: 'info' },
          { label: 'Learn Basic Cantonese', value: 'A few basic Cantonese phrases are appreciated.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free (90 days)', value: 'Israeli passport holders can enter Hong Kong visa-free for up to 90 days.', type: 'do' },
      { label: 'US/EU — Visa Free (90 days)', value: 'US and EU citizens can visit Hong Kong for up to 90 days without a visa.', type: 'info' },
      { label: 'Separate from China', value: 'Hong Kong has its own immigration policy. A visa for mainland China does NOT allow entry to Hong Kong, and vice versa.', type: 'dont' },
      { label: 'Arrival Registration', value: 'Complete the Hong Kong e-Channel registration to speed up immigration. Available to most nationalities.', type: 'tip' },
    ],
  },
  'abu-dhabi': {
    headline: 'Abu Dhabi blends rich Arabian heritage with ambitious modernity, offering a culturally deep experience beyond its glittering facade.',
    emoji: '🇦🇪',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Respectful Mosque Visit', value: 'When visiting the Sheikh Zayed Grand Mosque, remove your shoes and dress modestly, covering shoulders and knees.', type: 'do' },
          { label: 'Ramadan Observance', value: 'During the holy month of Ramadan, avoid eating, drinking, or smoking in public during daylight hours as a sign of respect.', type: 'dont' },
          { label: 'Cultural Openness', value: 'Abu Dhabi embraces cultural openness, welcoming visitors of all faiths to its iconic sites like the Grand Mosque.', type: 'info' },
          { label: 'Eid Celebrations', value: 'Experience the festive atmosphere during Eid al-Fitr and Eid al-Adha, which are major religious holidays.', type: 'tip' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Modest Attire', value: 'Dress modestly in public, especially when visiting religious sites, ensuring shoulders and knees are covered.', type: 'do' },
          { label: 'Swimwear at Beaches', value: 'Swimwear is acceptable at hotel pools and public beaches, but cover up when leaving these areas.', type: 'do' },
          { label: 'Avoid Revealing Clothes', value: 'Refrain from wearing overly revealing clothing in public spaces to respect local customs and sensibilities.', type: 'dont' },
          { label: 'Head Covering for Women', value: 'Women should carry a headscarf to cover their hair when entering mosques or other religious sites.', type: 'tip' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Daytime Ramadan Restrictions', value: 'During Ramadan, eating, drinking, and smoking in public during daylight hours are prohibited as a sign of respect.', type: 'dont' },
          { label: 'Alcohol Consumption', value: 'Alcohol is available in licensed hotels, clubs, and restaurants, but public consumption is generally prohibited.', type: 'info' },
          { label: 'Try Local Cuisine', value: 'Explore the diverse culinary scene, from traditional Emirati dishes to international fine dining.', type: 'tip' },
          { label: 'Hydrate Well', value: 'Drink plenty of water, especially during warmer months, to stay hydrated in the desert climate.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'Public Decency', value: 'Public displays of affection, loud music, and offensive gestures are not tolerated and can lead to legal issues.', type: 'dont' },
          { label: 'Photography Etiquette', value: 'Always ask for permission before photographing people, especially women, to respect their privacy.', type: 'do' },
          { label: 'Drug Laws', value: 'The UAE has a zero-tolerance policy for drugs, with severe penalties for possession, use, or trafficking.', type: 'dont' },
          { label: 'Respect Local Authority', value: 'Always comply with local laws and regulations, and respect the authority of law enforcement officials.', type: 'do' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Greetings', value: 'Use polite greetings like \'Assalamu Alaikum\' (peace be upon you) and respond with \'Wa Alaikum Assalam\'.', type: 'do' },
          { label: 'Public Behavior', value: 'Maintain a respectful demeanor in public spaces, avoiding overly loud conversations or boisterous behavior.', type: 'do' },
          { label: 'Bargaining in Souks', value: 'Bargaining is common in traditional souks; engage respectfully to get a good price.', type: 'tip' },
          { label: 'Show Gratitude', value: 'Express gratitude with \'Shukran\' (thank you) and be mindful of local customs regarding hospitality.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free', value: 'Israeli passport holders can enter the UAE (including Abu Dhabi) visa-free for up to 30 days since the Abraham Accords (2020).', type: 'do' },
      { label: 'US/EU — Visa on Arrival', value: 'US and EU citizens receive a free visa on arrival valid for 30 days, extendable once for another 30 days.', type: 'info' },
      { label: 'Passport Validity', value: 'Your passport must be valid for at least 6 months from your date of entry into the UAE.', type: 'tip' },
      { label: 'Abu Dhabi vs Dubai', value: 'Abu Dhabi is more conservative than Dubai. Dress modestly in public areas and avoid public displays of affection.', type: 'info' },
    ],
  },
  'ras-al-khaimah': {
    headline: 'Ras Al Khaimah offers an authentic Arabian experience with a focus on nature, adventure, and heritage, providing a less crowded and more affordable alternative to Dubai.',
    emoji: '🇦🇪',
    sections: [
      {
        id: 'religion',
        icon: 'moon.stars.fill',
        title: 'Religion & Customs',
        color: '#8B5CF6',
        gradient: ["#8B5CF6", "#6D28D9"] as [string, string],
        items: [
          { label: 'Visa Requirements', value: 'US, UK, EU, Australian, and most Western passport holders receive visa-on-arrival for 30 days. Check evisa.gov.ae for other nationalities.', type: 'info' },
          { label: 'Ramadan Restrictions', value: 'During the holy month, no eating, drinking, or smoking in public during daylight hours. Resort restaurants screen areas for non-fasting guests.', type: 'info' },
          { label: 'Respectful Visitors', value: 'Respectful visitors can still enjoy their holiday during Ramadan, but be mindful of local customs.', type: 'tip' },
        ],
      },
      {
        id: 'dress',
        icon: 'tshirt.fill',
        title: 'Dress Code',
        color: '#EC4899',
        gradient: ["#EC4899", "#BE185D"] as [string, string],
        items: [
          { label: 'Public Areas', value: 'Cover shoulders and knees in public areas out of respect for local customs.', type: 'do' },
          { label: 'Beach/Pool', value: 'Swimwear is fine at beaches and pools within resorts.', type: 'info' },
          { label: 'Resort Common Areas', value: 'Resorts are relaxed about beach coverups in common areas.', type: 'info' },
          { label: 'Old Town', value: 'Dress more conservatively when visiting the Old Town.', type: 'do' },
        ],
      },
      {
        id: 'food',
        icon: 'fork.knife',
        title: 'Food & Drink',
        color: '#F59E0B',
        gradient: ["#F59E0B", "#D97706"] as [string, string],
        items: [
          { label: 'Alcohol Availability', value: 'Alcohol is available at licensed hotels, resorts, and restaurants, but not sold in shops.', type: 'info' },
          { label: 'Local Specialties', value: 'Try fresh seafood, Machboos (spiced rice with meat/fish), and Luqaimat (sweet fried dumplings).', type: 'tip' },
          { label: 'Arabic Coffee & Dates', value: 'Arabic coffee and dates are deeply traditional and available everywhere.', type: 'info' },
          { label: 'Budget Eats', value: 'Old Town restaurants offer generous portions of Lebanese, Indian, and Yemeni food for 20-40 AED.', type: 'tip' },
        ],
      },
      {
        id: 'laws',
        icon: 'shield.fill',
        title: 'Laws & Rules',
        color: '#EF4444',
        gradient: ["#EF4444", "#B91C1C"] as [string, string],
        items: [
          { label: 'UAE-wide Rules', value: 'RAK follows UAE-wide rules regarding visas, currency, and alcohol consumption.', type: 'info' },
          { label: 'Alcohol Consumption', value: 'Alcohol is only permitted in licensed venues like hotels, resorts, and restaurants.', type: 'info' },
          { label: 'Ramadan Public Conduct', value: 'During Ramadan, avoid eating, drinking, or smoking in public during daylight hours.', type: 'dont' },
          { label: 'Safety', value: 'Ras Al Khaimah is extremely safe; crime against tourists is essentially nonexistent.', type: 'info' },
        ],
      },
      {
        id: 'etiquette',
        icon: 'hand.raised.fill',
        title: 'Etiquette & Tips',
        color: '#10B981',
        gradient: ["#10B981", "#059669"] as [string, string],
        items: [
          { label: 'Car Rental', value: 'Renting a car is highly recommended for independent travelers due to spread-out attractions and limited public transport.', type: 'tip' },
          { label: 'Visit Time', value: 'The best time to visit is November through March for perfect weather and outdoor activities.', type: 'tip' },
          { label: 'Value for Money', value: 'Luxury hotels and experiences are significantly cheaper than in Dubai, offering excellent value.', type: 'tip' },
          { label: 'Explore Beyond Resorts', value: 'Explore the Old Town, souks, and Dhayah Fort for an authentic Emirati atmosphere.', type: 'tip' },
        ],
      },
    ],
    visa: [
      { label: 'Israelis — Visa Free', value: 'Israeli passport holders can enter the UAE (including RAK) visa-free for up to 30 days since the Abraham Accords (2020).', type: 'do' },
      { label: 'US/EU — Visa on Arrival', value: 'US and EU citizens receive a free visa on arrival valid for 30 days, extendable once for another 30 days.', type: 'info' },
      { label: 'Passport Validity', value: 'Your passport must be valid for at least 6 months from your date of entry into the UAE.', type: 'tip' },
      { label: 'More Conservative', value: 'RAK is more traditional than Dubai. Dress modestly outside of resort areas and respect local customs.', type: 'info' },
    ],
  },
};

export const KNOWN_DESTINATIONS = Object.keys(TRAVI_CULTURAL_DATA);

export function getCulturalData(destination: string) {
  const key = destination?.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z-]/g, '');
  const d = TRAVI_CULTURAL_DATA[key];
  if (d) return d;
  // Try without hyphens
  const key2 = destination?.toLowerCase().replace(/[^a-z]/g, '');
  return TRAVI_CULTURAL_DATA[key2] ?? {
    headline: `Local culture and customs for ${destination}`,
    emoji: '🌍',
    sections: TRAVI_CULTURAL_DATA['dubai'].sections.map(s => ({ ...s, items: [
      { label: 'Research Local Customs', value: 'Check the dominant culture and customs before visiting places of worship.', type: 'tip' as const },
      { label: 'Dress Modestly', value: 'When in doubt, dress modestly. Locals will appreciate the respect.', type: 'do' as const },
      { label: 'Learn a Few Words', value: 'Hello, Thank you, and Sorry in the local language go a long way.', type: 'do' as const },
    ] })),
  };
}